version: 2.1

jobs:
    build:
        machine:
            image: ubuntu-2204
        steps:
        - checkout
        - run: |
             pwd
             apt update
             apt install -y --no-install-recommends autogen flex
             ./contrib/download_prerequisites
             mkdir build
             cd build
             ../configure --enable-threads=posix --enable-checking=release --disable-multilib --enable-languages=all #--enable-__cxa_atexit
             make
             make install-strip

workflows:
    build_and_test:
        jobs:
        - build
