version: 2.1

jobs:
    build:
        machine:
            image: ubuntu-2204:current
        steps:
        - checkout
        - run: |
             echo $CIRCLE_WORKING_DIRECTORY
             sudo docker info
             sudo apt update
             sudo apt install -y --no-install-recommends autogen flex podman uidmap
             podman info
             ./contrib/download_prerequisites
             mkdir build
             cd build
             ../configure --prefix=$CIRCLE_WORKING_DIRECTORY/product --enable-threads=posix --enable-checking=release --disable-multilib --enable-languages=all #--enable-__cxa_atexit
             make
             make install-strip

workflows:
    build_and_test:
        jobs:
        - build
